name = "air2lean"
version = "0.1.0"
defaultTargets = ["ZigLean", "Air2Lean", "air2lean"]

[[lean_lib]]
name = "ZigLean"

[[lean_lib]]
name = "Air2Lean"

[[lean_lib]]
name = "Proofs"
globs = ["Proofs.+"]

[[lean_exe]]
name = "air2lean"
root = "Air2Lean.Main"
