import FuturesFallible.Gen

/-! C08 runtime evidence for `--spawn-policy fallible`: `Io.async` may assign the task or run
it in the caller (`asyncWithPolicyC`). Every schedule and every policy choice is enumerated;
results are the same as with assignment, and both branches occur. Generated by the gate
(`check.sh`) into its work directory. -/

open Zig

private def require (ok : Bool) (message : String) : IO Unit :=
  unless ok do throw (IO.userError message)

/-- Every result of `main` over all schedules (each choice of each turn), at most `cap` runs. -/
partial def allOutcomes {Tgt α : Type} (dispatch : Tgt → ConcM Tgt Unit) (fuel cap : Nat)
    (main : ConcM Tgt α) (m0 : Mem) : Array (Option (Except Error α)) := Id.run do
  let mut out := #[]
  let mut todo : List (Array Nat) := [#[]]
  while !todo.isEmpty && out.size < cap do
    let pre := todo.head!
    todo := todo.tail!
    let (r, opts) := Sched.runTrace ⟨.any, .available⟩ dispatch fuel (fun i => pre.getD i 0) main m0
    out := out.push (r.map (·.map (·.1)))
    -- Branch on every later choice that this run took as 0.
    for i in [pre.size:opts.size] do
      for c in [1:opts[i]!] do
        todo := (pre ++ Array.replicate (i - pre.size) 0 |>.push c) :: todo
  return out

private def bv (n : Nat) : BitVec 32 := BitVec.ofNat 32 n

private def outcomes {α : Type} (x : ConcM FuturesFallible.Tgt α) : Array (Option (Except Error α)) :=
  allOutcomes FuturesFallible.dispatch 200 5000 x (FuturesFallible.mem0 .fresh)

private def onlyOk {α : Type} [BEq α] (rs : Array (Option (Except Error α))) (v : α) : Bool :=
  !rs.isEmpty && rs.all fun r => match r with
    | some (.ok a) => a == v
    | _ => false

def main : IO Unit := do
  for x in [0, 7, 4294967295] do
    require (onlyOk (outcomes (FuturesFallible.awaitValue ⟨⟩ (bv x))) (bv x * bv x))
      s!"fallible await did not return the task result for {x}"
    require (onlyOk (outcomes (FuturesFallible.awaitTwice ⟨⟩ (bv x))) (bv x * bv x + bv x * bv x))
      s!"fallible second await failed for {x}"
    require (onlyOk (outcomes (FuturesFallible.awaitOwned ⟨⟩ (bv x))) (bv x))
      s!"fallible captured pointer write lost for {x}"
    let canceled := outcomes (FuturesFallible.cancelValue ⟨⟩ (bv x))
    require (canceled.all fun r => match r with
        | some (.ok (.ok v)) => v == bv x + 1
        | some (.ok (.error e)) => e == "Canceled"
        | _ => false) s!"fallible cancel outcome outside result/Canceled for {x}"
    require (canceled.any (· matches some (.ok (.error _)))) s!"no assigned task observed Canceled for {x}"
    require (canceled.any (· matches some (.ok (.ok _)))) s!"no eager or early task completed for {x}"
  require (onlyOk (outcomes (FuturesFallible.awaitError ⟨⟩ 0)) (.error "Zero")) "fallible error not propagated"
  -- Both policy outcomes occur: one assigned run, one eager run of the same call.
  let traces := (List.range 2).map fun c =>
    (Sched.runTrace ⟨.any, .available⟩ FuturesFallible.dispatch 200 (fun _ => c) (FuturesFallible.awaitValue ⟨⟩ 3)
      (FuturesFallible.mem0 .fresh)).1 |>.bind fun r => match r with
        | .ok (_, m) => some m.threads.size
        | .error _ => none
  require (traces == [some 2, some 1]) s!"assigned and eager branches not both taken: {traces}"
  IO.println "futures fallible-policy runtime schedules passed"
