#!/usr/bin/env python3
"""Generate and check the current support matrix from committed sources.

`generate` rewrites the marked regions in docs/support-matrix.md, README.md and PLAN.md.
`check` exits 1 when a committed region is stale or when README, PLAN, ROADMAP, CI and the
translator CLI disagree about the facts the matrix is built from. Neither mode starts Zig,
Lake or Lean; `scripts/example-selection.sh` is sourced with bash.
"""
import argparse
import collections
import functools
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent
GENERATOR = 'scripts/support-matrix.py'
# Every committed input; tests copy exactly these into a scratch root.
SOURCES = [
    'README.md', 'PLAN.md', 'ROADMAP.md', 'docs/support-matrix.md',
    'scripts/example-selection.sh', 'scripts/check.sh', 'compatibility.json',
    'scripts/mutate.sh', 'scripts/translate.sh', 'zig-patch/versions.toml',
    'Air2Lean/Air/Normalize.lean', 'Air2Lean/Main.lean', 'Air2Lean/Diagnose.lean',
    '.github/workflows/ci.yml',
]
SOURCE_GLOBS = ['coverage/*.json', 'examples/*/zig-versions']
DEFAULT_SCRIPTS = ['scripts/check.sh', 'scripts/mutate.sh', 'scripts/translate.sh']
# scripts/doctor.sh delegates to scripts/doctor.py, whose default is the release metadata's.
DEFAULT_METADATA = 'compatibility.json'
STATUSES = ['complete', 'partial', 'open', 'research']
AREAS = collections.OrderedDict([
    ('T', 'Targets and profiles'), ('L', 'Language and representation'),
    ('C', 'Concurrency'), ('M', 'Memory and allocation'), ('F', 'Floats'),
    ('A', 'Inline assembly'), ('E', 'External boundaries'), ('P', 'Proof support'),
    ('I', 'Integration and tooling'), ('V', 'Validation and trust'),
    ('Q', 'Quality and testing'), ('D', 'Documentation'), ('X', 'Other source languages'),
])
REGIONS = {
    'docs/support-matrix.md': ['matrix'],
    'README.md': ['zig-versions'],
    'PLAN.md': ['zig-versions'],
}
OPEN_WORK_HEADING = '## Current open work'
HISTORY_HEADING = '## Historical milestones'


class Stale(Exception):
    pass


def read(root, rel):
    return (root/rel).read_text(encoding='utf-8')


def begin(name):
    return (f'<!-- support-matrix:begin {name} (generated by {GENERATOR}; '
            'do not edit by hand) -->')


def end(name):
    return f'<!-- support-matrix:end {name} -->'


# ---- committed facts -------------------------------------------------------------------------

def supported_versions(root):
    m = re.search(r'def supportedVersions : List String := \[([^\]]*)\]',
                  read(root, 'Air2Lean/Air/Normalize.lean'))
    if not m: raise Stale('Air2Lean/Air/Normalize.lean: supportedVersions not found')
    return re.findall(r'"([^"]+)"', m.group(1))


def pinned_versions(root):
    return re.findall(r'^\["([^"]+)"\]\s*$', read(root, 'zig-patch/versions.toml'), re.M)


def default_version(root):
    found = {}
    for rel in DEFAULT_SCRIPTS:
        m = re.search(r'^zig_version=\$\{AIR2LEAN_ZIG_VERSION:-([^}]+)\}', read(root, rel), re.M)
        if not m: raise Stale(f'{rel}: default AIR2LEAN_ZIG_VERSION not found')
        found[rel] = m.group(1)
    try:
        found[DEFAULT_METADATA] = json.loads(read(root, DEFAULT_METADATA))['zig']['default']
    except (ValueError, KeyError, TypeError):
        raise Stale(f'{DEFAULT_METADATA}: zig.default not found')
    if len(set(found.values())) != 1:
        raise Stale(f'default Zig versions disagree: {found}')
    return next(iter(found.values()))


def examples(root):
    return sorted(p.name for p in (root/'examples').iterdir() if p.is_dir())


@functools.lru_cache(maxsize=None)
def default_selection(root, version, arch='x86_64'):
    script = ('source "$1/scripts/example-selection.sh"; '
              'air2lean_default_examples "$1" "$2" "$3"')
    out = subprocess.run(['bash', '-c', script, 'support-matrix', str(root), version, arch],
                         check=True, capture_output=True, text=True).stdout
    return tuple(out.split())


def ci_matrix(root):
    """The `include` rows of the CI test matrix (a narrow parser: flat scalar keys only)."""
    text = read(root, '.github/workflows/ci.yml')
    m = re.search(r'^ +matrix:\n +include:\n(.*?)^ +steps:', text, re.M | re.S)
    if not m: raise Stale('.github/workflows/ci.yml: matrix include list not found')
    rows = []
    for line in m.group(1).splitlines():
        start = re.match(r'\s*- zig: "([^"]+)"\s*$', line)
        if start:
            rows.append({'zig': start.group(1)})
            continue
        key = re.match(r'\s+(examples|full|mutate|shard): (.*)$', line)
        if rows and key:
            rows[-1][key.group(1)] = key.group(2).strip().strip('"')
    return rows


def ci_jobs(root, version):
    rows = [r for r in ci_matrix(root) if r['zig'] == version]
    full = [r for r in rows if r.get('full') == 'true' and r.get('mutate') != 'true']
    restricted = [r for r in rows if r.get('full') != 'true' and r.get('mutate') != 'true']
    shards = [r for r in rows if r.get('mutate') == 'true']
    return full, restricted, shards


def coverage(root):
    out = {}
    for path in sorted((root/'coverage').glob('*.json')):
        data = json.loads(path.read_text(encoding='utf-8'))
        if path.stem != data.get('zig_version'):
            raise Stale(f'{path.relative_to(root)}: zig_version {data.get("zig_version")!r}')
        out[path.stem] = data
    return out


def register(root):
    rows = []
    for line in read(root, 'ROADMAP.md').splitlines():
        m = re.match(r'\| ([A-Z]\d\d) \| ([^|]+) \| (\w+) \|', line)
        if m:
            rows.append({'id': m.group(1), 'name': m.group(2).strip(), 'status': m.group(3)})
    if not rows: raise Stale('ROADMAP.md: requirement register not found')
    for row in rows:
        if row['status'] not in STATUSES:
            raise Stale(f'ROADMAP.md: {row["id"]} has unknown status {row["status"]!r}')
        if row['id'][0] not in AREAS:
            raise Stale(f'ROADMAP.md: {row["id"]} has an unknown area prefix')
    return rows


def lean_string(root, rel, name):
    """Concatenate the string literals of `def <name> : String := ...` up to a blank line."""
    text = read(root, rel)
    m = re.search(rf'^def {name} : String :=\n(.*?)\n\n', text, re.M | re.S)
    if not m: raise Stale(f'{rel}: def {name} not found')
    parts = re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))
    return re.sub(r'\\(.)', lambda e: '\n' if e.group(1) == 'n' else e.group(1), ''.join(parts))


def version_vote(versions, default):
    marked = [f'**{v}** (default)' if v == default else f'**{v}**' for v in versions]
    return marked[0] if len(marked) == 1 else ', '.join(marked[:-1]) + ' and ' + marked[-1]


# ---- generated regions -----------------------------------------------------------------------

@functools.lru_cache(maxsize=None)
def version_rows(root):
    versions = supported_versions(root)
    default = default_version(root)
    rows = []
    for v in versions:
        selected = default_selection(root, v)
        full, restricted, shards = ci_jobs(root, v)
        if full:
            ci = 'full job (pipeline, diff test, proofs)'
        elif restricted:
            ci = 'restricted job (translation and proofs; no diff harness)'
        else:
            ci = 'none'
        if shards: ci += f'; {len(shards)} mutation shards'
        rows.append({'version': v, 'default': v == default, 'examples': selected, 'ci': ci})
    return versions, default, rows


def region_zig_versions(root):
    versions, default, rows = version_rows(root)
    every = examples(root)
    lines = [f'Supported: Zig {version_vote(versions, default)}. Default example selection '
             '(`scripts/example-selection.sh` on x86_64; `asm` needs x86_64):', '',
             '| Zig | CI | Examples | Not selected |', '|---|---|---|---|']
    for row in rows:
        missing = [e for e in every if e not in row['examples']]
        lines.append(f'| {row["version"]}{" (default)" if row["default"] else ""} | {row["ci"]} | '
                     + ', '.join(f'`{e}`' for e in row['examples']) + ' | '
                     + (', '.join(f'`{e}`' for e in missing) or '—') + ' |')
    lines += ['', 'Full matrix: [docs/support-matrix.md](docs/support-matrix.md).']
    return '\n'.join(lines)


def region_matrix(root):
    versions, default, rows = version_rows(root)
    every = examples(root)
    cov = coverage(root)
    reg = register(root)
    out = ['## Zig versions', '',
           '| Zig | Default | Translator | Exporter pin | Coverage inventory | CI |',
           '|---|---|---|---|---|---|']
    pins = pinned_versions(root)
    for row in rows:
        v = row['version']
        out.append(f'| {v} | {"yes" if row["default"] else "no"} | `supportedVersions` | '
                   f'{"`zig-patch/versions.toml`" if v in pins else "missing"} | '
                   f'{"`coverage/" + v + ".json`" if v in cov else "missing"} | {row["ci"]} |')
    out += ['', '## Examples by version', '',
            'From `examples/*/zig-versions` through `scripts/example-selection.sh` '
            '(x86_64). An explicit `AIR2LEAN_EXAMPLES` selection bypasses it.', '',
            '| Example | ' + ' | '.join(versions) + ' |', '|---|' + '---|'*len(versions)]
    by_version = {row['version']: set(row['examples']) for row in rows}
    portable = {v: set(default_selection(root, v, 'aarch64')) for v in versions}
    for e in every:
        cells = ['yes' if e in by_version[v] else '—' for v in versions]
        x86 = any(e in by_version[v] and e not in portable[v] for v in versions)
        out.append(f'| `{e}`{" (x86_64 only)" if x86 else ""} | ' + ' | '.join(cells) + ' |')
    out += ['', '## Compiler-derived inventory', '',
            'Counts from `coverage/<version>.json` (`scripts/coverage.py`). This is a source '
            'inventory: it records no compiler execution, proof checking or support '
            'qualification ([docs/coverage.md](coverage.md)).', '']
    dispositions = sorted({k for data in cov.values() for k in data['summary']})
    out.append('| Zig | AIR tags | ' + ' | '.join(f'`{d}`' for d in dispositions)
               + ' | Type tags | Intern keys | Pointer bases | Model boundaries | '
               'Rejected model calls |')
    out.append('|---|' + '---:|'*(len(dispositions) + 5) + '---|')
    for v in versions:
        data = cov.get(v)
        if data is None:
            out.append(f'| {v} | missing |' + ' |'*(len(dispositions) + 5))
            continue
        rejected = sorted(m['name'] for m in data['models']
                          if m['disposition'] != 'recognized-model-boundary')
        out.append(f'| {v} | {len(data["tags"])} | '
                   + ' | '.join(str(data['summary'].get(d, 0)) for d in dispositions)
                   + f' | {len(data["types"])} | {len(data["constants"])} | '
                   f'{len(data["pointer_bases"])} | '
                   f'{len(data["models"]) - len(rejected)} | '
                   + (', '.join(f'`{n}`' for n in rejected) or '—') + ' |')
    counts = collections.Counter(r['status'] for r in reg)
    out += ['', '## Requirement register', '',
            f'From [ROADMAP.md](../ROADMAP.md): {len(reg)} requirements, '
            + ', '.join(f'{counts[s]} {s}' for s in STATUSES)
            + '. Only `complete` rows are finished; every other ID is current open work '
            '(acceptance in [remaining-acceptance.md](../remaining-acceptance.md)). '
            'A bounded merged slice does not complete a requirement.', '',
            '| Area | ' + ' | '.join(s.capitalize() for s in STATUSES) + ' |',
            '|---|' + '---|'*len(STATUSES)]
    for prefix, area in AREAS.items():
        cells = []
        for s in STATUSES:
            ids = [r['id'] for r in reg if r['id'][0] == prefix and r['status'] == s]
            cells.append(', '.join(ids) or '—')
        out.append(f'| {prefix}: {area} | ' + ' | '.join(cells) + ' |')
    return '\n'.join(out)


GENERATORS = {'matrix': region_matrix, 'zig-versions': region_zig_versions}


def replace_region(text, name, body, rel):
    b, e = begin(name), end(name)
    if text.count(b) != 1 or text.count(e) != 1 or text.index(b) > text.index(e):
        raise Stale(f'{rel}: expected one {name!r} region')
    head, rest = text.split(b, 1)
    _, tail = rest.split(e, 1)
    return f'{head}{b}\n{body}\n{e}{tail}'


def rendered(root):
    out = {}
    for rel, names in REGIONS.items():
        text = read(root, rel)
        for name in names:
            text = replace_region(text, name, GENERATORS[name](root), rel)
        out[rel] = text
    return out


# ---- agreement checks ------------------------------------------------------------------------

def consistency(root):
    problems = []
    versions = supported_versions(root)
    default = default_version(root)
    if default not in versions:
        problems.append(f'default Zig {default} is not in supportedVersions {versions}')
    pins = pinned_versions(root)
    if sorted(pins) != sorted(versions):
        problems.append(f'zig-patch/versions.toml pins {pins}, translator supports {versions}')
    cov = sorted(coverage(root))
    if cov != sorted(versions):
        problems.append(f'coverage inventories {cov}, translator supports {versions}')
    ci_rows = ci_matrix(root)
    ci_versions = sorted({r['zig'] for r in ci_rows})
    if ci_versions != sorted(versions):
        problems.append(f'CI matrix versions {ci_versions}, translator supports {versions}')
    for row in ci_rows:
        listed = row.get('examples', '').split()
        selected = list(default_selection(root, row['zig']))
        if listed and sorted(listed) != selected:
            problems.append(f'CI {row["zig"]} examples {listed} differ from the default '
                            f'selection {selected}')
    # CLI: help names every supported version, the default and the matrix; usage flags agree.
    help_text = lean_string(root, 'Air2Lean/Main.lean', 'help')
    usage_text = lean_string(root, 'Air2Lean/Main.lean', 'usage')
    for v in versions:
        if v not in help_text:
            problems.append(f'Air2Lean/Main.lean help does not name Zig {v}')
    if f'{default} (default)' not in help_text:
        problems.append(f'Air2Lean/Main.lean help does not mark {default} as the default')
    if 'docs/support-matrix.md' not in help_text:
        problems.append('Air2Lean/Main.lean help does not point to docs/support-matrix.md')
    for flag in sorted(set(re.findall(r'--[a-z][a-z-]*', usage_text))):
        if not re.search(rf'^\s+(?:-\w, )?{re.escape(flag)}(?![\w-])', help_text, re.M):
            problems.append(f'Air2Lean/Main.lean help does not describe {flag}')
    m = re.search(r'throw "usage: (air2lean --diagnostics-json[^"]*)"',
                  read(root, 'Air2Lean/Diagnose.lean'))
    if not m or m.group(1) not in usage_text:
        problems.append('Air2Lean/Main.lean usage differs from the --diagnostics-json usage '
                        'in Air2Lean/Diagnose.lean')
    # README: every example appears in the examples table.
    table = re.search(r'^\| Examples \| What they cover \|\n(.*?)\n\n',
                      read(root, 'README.md'), re.M | re.S)
    if not table: raise Stale('README.md: examples table not found')
    for e in examples(root):
        if not re.search(rf'^\|[^|\n]*`{re.escape(e)}`', table.group(1), re.M):
            problems.append(f'README.md examples table omits `{e}`')
    # ROADMAP: header counts equal the register.
    reg = register(root)
    counts = collections.Counter(r['status'] for r in reg)
    header = (f'**{len(reg)} requirements: {counts["complete"]} complete, '
              f'{counts["partial"]} partial, {counts["open"]} open and '
              f'{counts["research"]} research**')
    if header not in read(root, 'ROADMAP.md'):
        problems.append(f'ROADMAP.md header does not state {header}')
    # PLAN: history is marked historical; the open-work list repeats no completed work.
    plan = read(root, 'PLAN.md')
    if HISTORY_HEADING not in plan:
        problems.append(f'PLAN.md has no "{HISTORY_HEADING}" section')
    if OPEN_WORK_HEADING not in plan:
        problems.append(f'PLAN.md has no "{OPEN_WORK_HEADING}" section')
    else:
        section = plan.split(OPEN_WORK_HEADING, 1)[1].split('\n## ', 1)[0]
        status = {r['id']: r['status'] for r in reg}
        for rid in sorted(set(re.findall(r'\b[A-Z]\d\d\b', section))):
            if rid not in status:
                problems.append(f'PLAN.md open work names unknown requirement {rid}')
            elif status[rid] == 'complete':
                problems.append(f'PLAN.md open work repeats complete requirement {rid}')
        if re.search(r'\bdone\b', section, re.I):
            problems.append('PLAN.md open work lists an item as done')
        if '| T6 |' in section or '| T7 |' in section:
            problems.append('PLAN.md open work keeps historical T-series milestones')
    return problems


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('mode', choices=['generate', 'check'])
    parser.add_argument('--root', type=Path, default=ROOT)
    args = parser.parse_args(argv)
    root = args.root.resolve()
    # Selections are memoized within one run; a new run (or test) rereads the tree.
    default_selection.cache_clear()
    version_rows.cache_clear()
    try:
        texts = rendered(root)
        if args.mode == 'generate':
            for rel, text in texts.items():
                if read(root, rel) != text:
                    (root/rel).write_text(text, encoding='utf-8')
                    print(f'updated {rel}')
            problems = consistency(root)
        else:
            problems = [f'{rel}: generated region is stale; run python3 {GENERATOR} generate'
                        for rel, text in texts.items() if read(root, rel) != text]
            problems += consistency(root)
    except (Stale, OSError, ValueError, KeyError, subprocess.CalledProcessError) as error:
        print(f'support-matrix: {error}', file=sys.stderr)
        return 2
    for problem in problems:
        print(f'support-matrix: {problem}', file=sys.stderr)
    if problems: return 1
    if args.mode == 'check': print('support matrix current')
    return 0


if __name__ == '__main__':
    sys.exit(main())
