#!/usr/bin/env python3
"""Generate the wide integer bit-operation corpus: wide.zig, native.zig and Diff.lean.inc.

One exported function per (width, signedness), `ops_<u|i><W>(sel, hi, lo, k) u128`, selects the
operation by `sel`; the operand is the low W bits of hi:lo and `k` is the shift count. Results are
the W-bit pattern, zero-extended and split into 128-bit halves (`sel` + 16 selects the high half).
The same row tables drive the native program and the Lean evaluation, so both print identical
rows. `gen.py --check` fails when the committed files are stale.

Runtime safety stays on, so a shift count of at least W (representable when W is not a power of
two) reaches Zig's `shiftRhsTooBig` safety check. Those rows are illegal behavior in ReleaseFast and
ReleaseSmall and are kept out of the main corpus; `panics.zig` runs them in Debug and ReleaseSafe,
where every one must panic, and the Lean side prints the `Zig.Error` it throws (`P ` rows).
"""
import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
WIDTHS = [3, 7, 24, 40, 65, 72, 100, 127, 128, 129, 200]
# sel: 0 clz, 1 ctz, 2 popCount, 3 shl, 4 shl overflow flag, 5 @shlWithOverflow value,
# 6 shr (arithmetic for signed), 7 byteSwap (W % 8 == 0), 8 bitReverse; +16 is the high half.
COUNTS = [0, 1, 2]
SHIFTS = [3, 4, 5, 6]
SHIFT_SELS = SHIFTS + [19, 21, 22]
# The checked shifts (`<<`, `>>`); `@shlWithOverflow` has no count check (unchecked illegal).
CHECKED_SHIFTS = [3, 6]
SHIFT_PANIC = "shift amount is greater than the type size"


def log2_bits(w):
    return (w - 1).bit_length()


def values(w, signed):
    m = (1 << w) - 1
    s = 1 << (w - 1)
    out = [0, 1, 2, 3, m, s, s - 1, s + 1, m - 1, (m // 3) & m, (m // 3 * 2) & m,
           (1 << (w // 2)) - 1, 1 << (w // 2)]
    x = 0x9E3779B97F4A7C15 * w + (1 if signed else 0)
    for _ in range(4):
        x = (x * 6364136223846793005 + 1442695040888963407) % (1 << 64)
        y = (x * 2862933555777941757 + 3037000493) % (1 << 64)
        out.append((y ^ (x << 17) ^ (y << 71) ^ (x << 130)) & m)
    seen, res = set(), []
    for v in out:
        if v not in seen:
            seen.add(v)
            res.append(v)
    return res


def shift_counts(w):
    if w <= 40:
        return list(range(w))
    ks = {0, 1, 2, 3, 7, 8, 9, 31, 32, 33, 63, 64, 65, 100, 127, 128, 129, 199}
    ks |= {w // 2 - 1, w // 2, w // 2 + 1, w - 2, w - 1}
    return sorted(k for k in ks if 0 <= k < w)


def panic_counts(w):
    """Illegal counts of the W-bit shift (`u<log2>` holds up to 2^log2 - 1), plus the legal W - 1
    as a non-panicking control."""
    top = (1 << log2_bits(w)) - 1
    return sorted({w - 1} | {k for k in (w, w + 1, (w + top) // 2, top) if w <= k <= top})


def panic_rows():
    """(tag, sel, value, count) rows of panics.zig: non-power-of-two widths only."""
    rows = []
    for w, signed in combos():
        if len(panic_counts(w)) == 1:
            continue
        sels = CHECKED_SHIFTS + ([s + 16 for s in CHECKED_SHIFTS] if w > 128 else [])
        for v in (1, (1 << w) - 1):
            rows += [(tag(w, signed), sel, v, k) for sel in sels for k in panic_counts(w)]
    return rows


def plain_sels(w):
    sels = COUNTS + ([7] if w % 8 == 0 else []) + [8]
    return sels + ([s + 16 for s in sels[3:]] if w > 128 else [])


def shift_sels(w):
    return SHIFTS + ([19, 21, 22] if w > 128 else [])


def combos():
    return [(w, s) for w in WIDTHS for s in (False, True)]


def tag(w, signed):
    return f"{'i' if signed else 'u'}{w}"


def zig_fn(w, signed):
    t = tag(w, signed)
    u = f"u{w}"
    hi = w > 128
    lines = [f"pub export fn ops_{t}(sel: u32, hi: u128, lo: u128, k: u32) u128 {{",
             "    const wide: u256 = (@as(u256, hi) << 128) | lo;",
             f"    const x: {t} = @bitCast(@as({u}, @truncate(wide)));",
             f"    const amt: u{log2_bits(w)} = @intCast(k);",
             "    return switch (sel) {",
             "        0 => @as(u128, @clz(x)),", "        1 => @as(u128, @ctz(x)),",
             "        2 => @as(u128, @popCount(x)),"]

    def pat(expr):
        return f"@as(u256, @as({u}, @bitCast({expr})))"
    ops = [(3, "x << amt"), (5, "@shlWithOverflow(x, amt)[0]"), (6, "x >> amt"), (8, "@bitReverse(x)")]
    if w % 8 == 0:
        ops.append((7, "@byteSwap(x)"))
    for sel, expr in ops:
        lines.append(f"        {sel} => @as(u128, @truncate({pat(expr)})),")
        if hi:
            lines.append(f"        {sel + 16} => @as(u128, @truncate({pat(expr)} >> 128)),")
    lines.append("        4 => @as(u128, @shlWithOverflow(x, amt)[1]),")
    lines += ["        else => 0,", "    };", "}"]
    return "\n".join(lines)


def nums(xs):
    return ", ".join(str(x) for x in xs)


def zig_sources():
    wide = ["//! Generated by gen.py. Wide and odd-width integer bit operations.", ""]
    nat = ["//! Generated by gen.py. Native observations for wide.zig.",
           "const std = @import(\"std\");", "const wide = @import(\"wide\");", "",
           "fn emit(tag: []const u8, sel: u32, v: u256, k: u32, r: u128) void {",
           "    std.debug.print(\"{s} {d} {d} {d} {d}\\n\", .{ tag, sel, v, k, r });", "}", ""]
    main = []
    for w, signed in combos():
        t = tag(w, signed)
        wide += [zig_fn(w, signed), ""]
        call = f"wide.ops_{t}(sel, @truncate(v >> 128), @truncate(v), %s)"
        nat += [f"fn run_{t}() void {{",
                f"    const vals = [_]u256{{ {nums(values(w, signed))} }};",
                f"    const ks = [_]u32{{ {nums(shift_counts(w))} }};",
                f"    const plain = [_]u32{{ {nums(plain_sels(w))} }};",
                f"    const shifts = [_]u32{{ {nums(shift_sels(w))} }};",
                "    for (vals) |v| {",
                f"        for (plain) |sel| emit(\"{t}\", sel, v, 0, {call % '0'});",
                "        for (shifts) |sel| for (ks) |k|",
                f"            emit(\"{t}\", sel, v, k, {call % 'k'});",
                "    }", "}", ""]
        main.append(f"    run_{t}();")
    nat += ["pub fn main() void {"] + main + ["}", ""]
    return "\n".join(wide), "\n".join(nat), panics_source()


def panics_source():
    rows = [f"    .{{ .tag = \"{t}\", .sel = {sel}, .v = {v}, .k = {k}, .f = wide.ops_{t} }},"
            for t, sel, v, k in panic_rows()]
    return "\n".join([
        "//! Generated by gen.py. Shift counts >= W of wide.zig; Debug and ReleaseSafe only.",
        "//! The panic handler prints the row and resumes with the next one (the abandoned frames",
        "//! stay on the stack; there are few rows).",
        "const std = @import(\"std\");", "const wide = @import(\"wide\");", "",
        "pub const panic = std.debug.FullPanic(onPanic);", "",
        "const Row = struct {", "    tag: []const u8,", "    sel: u32,", "    v: u256,", "    k: u32,",
        "    f: *const fn (u32, u128, u128, u32) callconv(.c) u128,", "};", "",
        "const rows = [_]Row{", *rows, "};", "",
        "var next: usize = 0;", "",
        "fn onPanic(msg: []const u8, _: ?usize) noreturn {",
        "    const r = rows[next - 1];",
        f"    const kind = if (std.mem.eql(u8, msg, \"{SHIFT_PANIC}\")) \"shiftRhsTooBig\" else \"other\";",
        "    std.debug.print(\"P {s} {d} {d} {d} panic {s}\\n\", .{ r.tag, r.sel, r.v, r.k, kind });",
        "    runRows();", "}", "",
        "fn runRows() noreturn {",
        "    while (next < rows.len) {",
        "        const r = rows[next];", "        next += 1;",
        "        const x = r.f(r.sel, @truncate(r.v >> 128), @truncate(r.v), r.k);",
        "        std.debug.print(\"P {s} {d} {d} {d} ok {d}\\n\", .{ r.tag, r.sel, r.v, r.k, x });",
        "    }", "    std.process.exit(0);", "}", "",
        "pub fn main() void {", "    runRows();", "}", ""])


def lean_source():
    out = ["/-! Generated by gen.py. Append to the translation of wide.zig (namespace Wide), then run. -/",
           "private def wideValue {α : Type} (label : String) (r : Zig.Result α) : IO α :=",
           "  match r.run with",
           "  | some (.ok value) => pure value",
           "  | _ => throw (IO.userError s!\"unexpected wide result: {label}\")", "",
           "private def emit (tag : String) (sel : Nat) (v : Nat) (k : Nat)",
           "    (f : BitVec 32 → BitVec 128 → BitVec 128 → BitVec 32 → Zig.Result (BitVec 128)) : IO Unit := do",
           "  let r ← wideValue tag (f (BitVec.ofNat 32 sel) (BitVec.ofNat 128 (v >>> 128))",
           "    (BitVec.ofNat 128 (v % 2 ^ 128)) (BitVec.ofNat 32 k))",
           "  IO.println s!\"{tag} {sel} {v} {k} {r.toNat}\"", ""]
    main = []
    for w, signed in combos():
        t = tag(w, signed)
        out += [f"def run_{t} : IO Unit := do",
                f"  let vals : Array Nat := #[{nums(values(w, signed))}]",
                f"  let ks : Array Nat := #[{nums(shift_counts(w))}]",
                f"  let plain : Array Nat := #[{nums(plain_sels(w))}]",
                f"  let shifts : Array Nat := #[{nums(shift_sels(w))}]",
                "  for v in vals do",
                f"    for sel in plain do emit \"{t}\" sel v 0 Wide.ops_{t}",
                "    for sel in shifts do",
                f"      for k in ks do emit \"{t}\" sel v k Wide.ops_{t}", ""]
        main.append(f"  run_{t}")
    out += ["/-- A `panics.zig` row: the value, or the `Zig.Error` constructor thrown. -/",
            "private def emitP (tag : String) (sel : Nat) (v : Nat) (k : Nat)",
            "    (f : BitVec 32 → BitVec 128 → BitVec 128 → BitVec 32 → Zig.Result (BitVec 128)) : IO Unit :=",
            "  let r := match (f (BitVec.ofNat 32 sel) (BitVec.ofNat 128 (v >>> 128))",
            "      (BitVec.ofNat 128 (v % 2 ^ 128)) (BitVec.ofNat 32 k)).run with",
            "    | some (.ok x) => s!\"ok {x.toNat}\"",
            "    | some (.error e) => s!\"panic {(reprStr e).replace \"Zig.Error.\" \"\"}\"",
            "    | none => \"diverge\"",
            "  IO.println s!\"P {tag} {sel} {v} {k} {r}\"", "",
            "def run_panics : IO Unit := do"]
    out += [f"  emitP \"{t}\" {sel} {v} {k} Wide.ops_{t}" for t, sel, v, k in panic_rows()]
    out += ["", "def main : IO Unit := do"] + main + ["  run_panics", ""]
    return "\n".join(out)


def outputs():
    wide, nat, panics = zig_sources()
    return {"wide.zig": wide, "native.zig": nat, "panics.zig": panics, "Diff.lean.inc": lean_source()}


def exports():
    return [f"ops_{tag(w, s)}" for w, s in combos()]


def row_count():
    return sum(len(values(w, s)) * (len(plain_sels(w)) + len(shift_sels(w)) * len(shift_counts(w)))
               for w, s in combos())


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--count", action="store_true")
    a = ap.parse_args()
    if a.count:
        print(row_count())
        sys.exit(0)
    stale = False
    for name, text in outputs().items():
        p = HERE / name
        if a.check:
            if not p.exists() or p.read_text() != text:
                print(f"stale generated file: {name}", file=sys.stderr)
                stale = True
        else:
            p.write_text(text)
    sys.exit(1 if stale else 0)
