//! Generated by gen.py. Wide and odd-width integer bit operations.

pub export fn ops_u3(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: u3 = @bitCast(@as(u3, @truncate(wide)));
    const amt: u2 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u3, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u3, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u3, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u3, @bitCast(@bitReverse(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_i3(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: i3 = @bitCast(@as(u3, @truncate(wide)));
    const amt: u2 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u3, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u3, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u3, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u3, @bitCast(@bitReverse(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_u7(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: u7 = @bitCast(@as(u7, @truncate(wide)));
    const amt: u3 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u7, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u7, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u7, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u7, @bitCast(@bitReverse(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_i7(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: i7 = @bitCast(@as(u7, @truncate(wide)));
    const amt: u3 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u7, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u7, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u7, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u7, @bitCast(@bitReverse(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_u24(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: u24 = @bitCast(@as(u24, @truncate(wide)));
    const amt: u5 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u24, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u24, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u24, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u24, @bitCast(@bitReverse(x)))))),
        7 => @as(u128, @truncate(@as(u256, @as(u24, @bitCast(@byteSwap(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_i24(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: i24 = @bitCast(@as(u24, @truncate(wide)));
    const amt: u5 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u24, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u24, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u24, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u24, @bitCast(@bitReverse(x)))))),
        7 => @as(u128, @truncate(@as(u256, @as(u24, @bitCast(@byteSwap(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_u40(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: u40 = @bitCast(@as(u40, @truncate(wide)));
    const amt: u6 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u40, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u40, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u40, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u40, @bitCast(@bitReverse(x)))))),
        7 => @as(u128, @truncate(@as(u256, @as(u40, @bitCast(@byteSwap(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_i40(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: i40 = @bitCast(@as(u40, @truncate(wide)));
    const amt: u6 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u40, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u40, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u40, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u40, @bitCast(@bitReverse(x)))))),
        7 => @as(u128, @truncate(@as(u256, @as(u40, @bitCast(@byteSwap(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_u65(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: u65 = @bitCast(@as(u65, @truncate(wide)));
    const amt: u7 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u65, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u65, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u65, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u65, @bitCast(@bitReverse(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_i65(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: i65 = @bitCast(@as(u65, @truncate(wide)));
    const amt: u7 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u65, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u65, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u65, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u65, @bitCast(@bitReverse(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_u72(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: u72 = @bitCast(@as(u72, @truncate(wide)));
    const amt: u7 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u72, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u72, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u72, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u72, @bitCast(@bitReverse(x)))))),
        7 => @as(u128, @truncate(@as(u256, @as(u72, @bitCast(@byteSwap(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_i72(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: i72 = @bitCast(@as(u72, @truncate(wide)));
    const amt: u7 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u72, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u72, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u72, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u72, @bitCast(@bitReverse(x)))))),
        7 => @as(u128, @truncate(@as(u256, @as(u72, @bitCast(@byteSwap(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_u100(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: u100 = @bitCast(@as(u100, @truncate(wide)));
    const amt: u7 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u100, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u100, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u100, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u100, @bitCast(@bitReverse(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_i100(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: i100 = @bitCast(@as(u100, @truncate(wide)));
    const amt: u7 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u100, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u100, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u100, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u100, @bitCast(@bitReverse(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_u127(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: u127 = @bitCast(@as(u127, @truncate(wide)));
    const amt: u7 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u127, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u127, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u127, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u127, @bitCast(@bitReverse(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_i127(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: i127 = @bitCast(@as(u127, @truncate(wide)));
    const amt: u7 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u127, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u127, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u127, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u127, @bitCast(@bitReverse(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_u128(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: u128 = @bitCast(@as(u128, @truncate(wide)));
    const amt: u7 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u128, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u128, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u128, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u128, @bitCast(@bitReverse(x)))))),
        7 => @as(u128, @truncate(@as(u256, @as(u128, @bitCast(@byteSwap(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_i128(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: i128 = @bitCast(@as(u128, @truncate(wide)));
    const amt: u7 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u128, @bitCast(x << amt))))),
        5 => @as(u128, @truncate(@as(u256, @as(u128, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        6 => @as(u128, @truncate(@as(u256, @as(u128, @bitCast(x >> amt))))),
        8 => @as(u128, @truncate(@as(u256, @as(u128, @bitCast(@bitReverse(x)))))),
        7 => @as(u128, @truncate(@as(u256, @as(u128, @bitCast(@byteSwap(x)))))),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_u129(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: u129 = @bitCast(@as(u129, @truncate(wide)));
    const amt: u8 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(x << amt))))),
        19 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(x << amt))) >> 128)),
        5 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        21 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(@shlWithOverflow(x, amt)[0]))) >> 128)),
        6 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(x >> amt))))),
        22 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(x >> amt))) >> 128)),
        8 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(@bitReverse(x)))))),
        24 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(@bitReverse(x)))) >> 128)),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_i129(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: i129 = @bitCast(@as(u129, @truncate(wide)));
    const amt: u8 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(x << amt))))),
        19 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(x << amt))) >> 128)),
        5 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        21 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(@shlWithOverflow(x, amt)[0]))) >> 128)),
        6 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(x >> amt))))),
        22 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(x >> amt))) >> 128)),
        8 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(@bitReverse(x)))))),
        24 => @as(u128, @truncate(@as(u256, @as(u129, @bitCast(@bitReverse(x)))) >> 128)),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_u200(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: u200 = @bitCast(@as(u200, @truncate(wide)));
    const amt: u8 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(x << amt))))),
        19 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(x << amt))) >> 128)),
        5 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        21 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(@shlWithOverflow(x, amt)[0]))) >> 128)),
        6 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(x >> amt))))),
        22 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(x >> amt))) >> 128)),
        8 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(@bitReverse(x)))))),
        24 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(@bitReverse(x)))) >> 128)),
        7 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(@byteSwap(x)))))),
        23 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(@byteSwap(x)))) >> 128)),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}

pub export fn ops_i200(sel: u32, hi: u128, lo: u128, k: u32) u128 {
    @setRuntimeSafety(false); // counts >= W are excluded; the checked panic path is not translated
    const wide: u256 = (@as(u256, hi) << 128) | lo;
    const x: i200 = @bitCast(@as(u200, @truncate(wide)));
    const amt: u8 = @intCast(k);
    return switch (sel) {
        0 => @as(u128, @clz(x)),
        1 => @as(u128, @ctz(x)),
        2 => @as(u128, @popCount(x)),
        3 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(x << amt))))),
        19 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(x << amt))) >> 128)),
        5 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(@shlWithOverflow(x, amt)[0]))))),
        21 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(@shlWithOverflow(x, amt)[0]))) >> 128)),
        6 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(x >> amt))))),
        22 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(x >> amt))) >> 128)),
        8 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(@bitReverse(x)))))),
        24 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(@bitReverse(x)))) >> 128)),
        7 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(@byteSwap(x)))))),
        23 => @as(u128, @truncate(@as(u256, @as(u200, @bitCast(@byteSwap(x)))) >> 128)),
        4 => @as(u128, @shlWithOverflow(x, amt)[1]),
        else => 0,
    };
}
